### PR TITLE
Use Dirac API for Dirac proxy checking and checking for gbasf2 project existance

### PR DESCRIPTION
**Pull request by meliache**
So far the gbasf2 batch had been parsing the output of ``gb2_job_status -p <project>`` to see if the project already has been submitted to the grid or not. But I already had a script which directly interacts with the [Dirac API](https://github.com/DIRACGrid/DIRAC/blob/integration/Interfaces/API/Dirac.py) and returns a json job status dictionary. So I now use that to also see if the project exists by return with a special exit code (currently 3) if no jobs had been found for that project name.

This is solves part of #47. 

One reason I didn't do that earlier is, because I don't fully understand the Dirac API. They seem to work mostly with return values instead of with exceptions and. And as of now I assume that if the return value of the dirac API, when querying for jobs in a project, is `status["OK"] == False`, that it means that there are no jobs for that project. But I am not sure what happens if any other exception happens on the dirac side of things, whether I will be able to distinguish between "no jobs" and a dirac error. But I just hope that dirac will actually raise an exception if something really unexpected happens.

## Description Update 2020-10-30

I forgot to mention that this PR also implements using the Dirac API for checking whether the dirac proxy is alive. This is how I started working on this branch and the project existance checking was just something I decided to add because I thought it should be simple, but when I created this PR I had first forgotten that the proxy checking is also part of this branch and somehow thought it is already merged.

## Discussion: Communication with Dirac API handler subprocesses

I use python2 scripts in subprocesses for handling the Dirac API. However, I have no well-defined way of communicating with these subprocesses yet. I wanted to go away from the  string parsing that I used with the existing gbasf2 executables. For getting complex data from subprocesses I use json. For getting boolean information I currently use exit codes. E.g. the job status getter uses both. 

However, maybe it's better to only use json for communication and not use exit codes for anything that is not an error? 

And if I keep using exit codes, I should use the allowed custom values and define them somewhere globally, e.g. in an enum. Just have to think of a way that works both in python3 and python2.

### CODE REVIEW

**Review by welschma — APPROVED** [review]
Tested the changes in this branch with gbasf2 v4r7p4, everything seems to be working again. Without the new handling of the job status, we cannot use the gbasf2 batch process withe the new gbasf2 version.

**Comment by alina-ma** [comment]
Also tested it with gbasf2 v4r7p4 and it fixed the problem that the job status could not be determined, which occurred in the new gbasf2 version.

**Comment by nils-braun** [comment]
So, @meliache ready to merge?

**Comment by nils-braun** [comment]
Thanks to @meliache for the nice PR (as always) and thanks to @welschma and @alina-ma for checking.
@meliache I would still suggestion to make you an admin of this repo so you can take over the development (or also @welschma if he prefers). I am not sure I will be able to look into things quite often.
At least the gbasf2 part I can even check - in the core part you can if course still ask me for a review.

**Comment by meliache** [comment]
Ready to merge 👍 . As always, I have ideas for things I could add (see all the issues I created for myself), but let's keep this PR as is.

I'd accept the admin request. The gbasf2 part is getting more users and sometimes it would be good to be able to react quickly to upstream changes in gbasf2 (a major release will come soon which I expect might break some workflows again). Usually, I redirect people to my fork, but it would be simpler to just have the hotfixes here (at least on a branch). And would be nice to have feature branches here instead of on my fork. I wouldn't mind having Max as a co-admin, I ask him for review/tests anyway.

Off-topic note to myself: I start to think I need to think of a testing strategy for the gbasf2 wrapper, even something rudimentary would help. So far I didn't do unit tests because it  requires a special environment with CentOS7, a gbasf2 installation and a grid certificate. But for that I could simply start creating some tests which are not part of the CI and I can run manually in the right environment whenever a new gbasf2 release comes out etc.. So far I only check whether the example task works, so I could extend on that...

**Comment by meliache** [comment]
Should I maybe bump the version?

**Pull request merged**
